[package]
name = "use-aggregator"
version = "0.1.0"
authors = ["coder"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aggregator = { path = "../aggregator" }
